apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hmq-chart.fullname" . }}
  labels:
    {{- include "hmq-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hmq-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hmq-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port.mqtt }}
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-configmap
              mountPath: /conf
              subPath: hmq.config
      volumes:
        - name: {{ .Release.Name }}-configmap
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: hmq.config
                path: hmq.config
