apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmq-chart.fullname" . }}
  labels:
    {{- include "hmq-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
    - name: mqtt
      port: {{ .Values.service.port.mqtt }}
    - name: http
      port: {{ .Values.service.port.http }}
  selector:
    {{- include "hmq-chart.selectorLabels" . | nindent 4 }}
