name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run unit-tests and code coverage
        uses: docker/build-push-action@v2
        with:
          context: .
          target: unit-test-coverage
          file: ./Dockerfile
          push: false
